default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #host: localhost

development:
  <<: *default
  database: hinquiz_db_development
  # username: postgres
  # password: postgres
  # host: localhost
  password: password

test:
  <<: *default
  database: hinquiz_db_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: hinquiz_db
  #username: rails

#  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
  #username: bablu_dev
  password: 'password'